version: '3.8'
services:
    app:
        image: 'php:8.2-fpm'
        container_name: laravel_app
        ports:
            - '8000:8000'
        volumes:
            - '.:/var/www/html'
        working_dir: /var/www/html
        depends_on:
            - db
    webserver:
        image: 'nginx:alpine'
        container_name: nginx_web
        ports:
            - '80:80'
        volumes:
            - '.:/var/www/html'
            - './nginx.conf:/etc/nginx/conf.d/default.conf'
        depends_on:
            - app
    db:
        image: 'mysql:5.7'
        container_name: mysql_db
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - 'dbdata:/var/lib/mysql'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: laravel
            PMA_PASSWORD: secret
        depends_on:
            - db
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
volumes:
    dbdata: null
    sail-mysql:
        driver: local
